services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=easysales
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DATABASE=easysales
    ports:
      - "5432:5432"
    volumes:
      - /Documents/postgres/easysales:/var/lib/postgresql/data
