spring:
  datasource:
    url: jdbc:postgresql://dpg-cn2nkeq1hbls73bad4eg-a/easysales
    #url:jdbc:postgres://easysales_db:Kshp1UelWPReZsELRoWTCS9594RAAE4H@dpg-cn2nkeq1hbls73bad4eg-a.oregon-postgres.render.com/easysales:
    username: easysales_db
    password: Kshp1UelWPReZsELRoWTCS9594RAAE4H
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
